apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "#{{DeployName}}#-azure-key-vault"
  namespace: "#{{Namespace}}#"
spec:
  provider:
    azurekv:
      tenantId: "#{{TenantId}}#"
      vaultUrl: "#{{VaultUrl}}#"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
